GET http://localhost:3003/classes/ HTTP/1.1

###

GET http://localhost:3003/students/ HTTP/1.1

###

POST http://localhost:3003/classes/

###

POST http://localhost:3003/students/

{
    "id": 1,
    "class": "ReactJS"
}


{
    "id": 2,
    "class_id": 3,
    "name": "Hoa",
    "gender": "female",
    "dob": "13/11/2001",
    "email": "hoa1311@gmail.com",
    "address": "Ha Giang"
}


