const actionName =  {

    GET_STUDENTS: 'GET_STUDENTS',
    ADD_STUDENTS: 'ADD_STUDENTS',
    DELETE_STUDENTS: 'DELETE_STUDENTS',
    EDIT_STUDENTS: 'EDIT_STUDENTS',
    GET_STUDENTBYID: 'GET_STUDENTBYID',
    SET_STUDENT: 'SET_STUDENT',

    GET_CLASSES: 'GET_CLASSES',
    ADD_CLASSES: 'ADD_CLASSES',
    DELETE_CLASSES: 'DELETE_CLASSES',
    EDIT_CLASSES: 'EDIT_CLASSES',
    GET_CLASSESBYID: 'GET_CLASSESBYID',
    SET_CLASS: 'SET_CLASS',
}

export default actionName