const actionName =  {

    GET_STUDENTS: 'GET_STUDENTS',
    ADD_STUDENTS: 'ADD_STUDENTS',
    DELETE_STUDENTS: 'DELETE_STUDENTS',
    EDIT_STUDENTS: 'EDIT_STUDENTS',
    GET_STUDENTBYID: 'GET_STUDENTBYID',
    SET_STUDENT: 'SET_STUDENT',
}

export default actionName